- hosts: servers

  vars:
    root_dir: /usr/share/nginx/html
    web_server: "This is server {{ ansible_hostname }}" 
    date: "{{ ansible_date_time['date'] }} {{ ansible_date_time['time'] }} "

  tasks:
    - name: Install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: present
      become: yes

    - name: Print message
      ansible.builtin.command: "cowsay 'This is server {{ ansible_hostname }}!'"
      register: cowsay_result
    
    - name: Debug cowsay result
      ansible.builtin.debug:
        msg: "{{ cowsay_result.stdout }}"

    - name: copy HTML 
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: '{{ root_dir }}/index.html.j2'
      become: yes

    
      