- hosts: servers
  gather_facts: no
  vars:
    users:
      - jaime
      - santa
      - robert
  tasks:
    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
      become: yes

    - name: create config
      ansible.builtin.template:
        src: files/.gitconfig
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ users }}"
      become: yes

    - name: create .ssh directory
      ansible.builtin.file:
        path: '/home/{{ item }}/.ssh'
        state: directory
      loop: "{{ users }}"
      become: yes

    - name: copy public key
      ansible.builtin.copy:
        src: files/id_rsa.pub
        dest: '/home/{{ item }}/.ssh/authorized_keys'
      loop: '{{ users }}'
      become: yes

